# Generated by Django 3.2 on 2022-03-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtct',
            new_name='Product',
        ),
    ]
